### ISSUE TITLE
0day.today causes exception

### ISSUE THREAD

**Issue by narunask** [rfunix/Pompem#14]
It seems that non existing domain `0day.today` causes the following exception:

```
Traceback (most recent call last):
  File "/home/narunas/Pompem/env/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/narunas/Pompem/env/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:
<...>
```

`Pompem` however does output results from the other resources...

IMHO exception handling could be done in more user friendly way. Rather than printing exception trace it could be logged to the file, users should see just a short message, describing the problem on the runtime.

**Comment by rfunix** [comment]
Hi @narunask,

I will check it !

Thanks !

**Comment by rfunix** [comment]
I'm working on a new version of Pompem, https://github.com/rfunix/Pompem/tree/pompem_v3 , and in that version 0day is working fine =) Check it
