### ISSUE TITLE
Vulners detects bots

### ISSUE THREAD

**Issue by JJK96** [rfunix/Pompem#26]
```
Traceback (most recent call last):
  File "/home/jjk/git/Pompem/core/scrapers.py", line 28, in _get_results
    self._parser(html)
  File "/home/jjk/git/Pompem/core/scrapers.py", line 188, in _parser
    for data in json_data['data']['search']:
KeyError: 'search'
```

When debugging I find that the following response is received from Vulners:

```
{
  "result": "error",
  "data": {
    "error": "Looks like you are a bot. Please, pass captcha or obtain proper valid API key",
    "errorCode": 9000
  }
}
```

**Comment by Yashsomalkar** [comment]
same with me :(

**Comment by lapers** [comment]
The same problem

**Comment by vulnersCom** [comment]
You need just use API key with the request.
